import ast
import hashlib
import textwrap
import itertools
from typing import List, Dict, Any, Optional, Tuple, Set
from pathlib import Path
import logging
from .parser import FunctionShard, ClassShard, ModuleShard
from .filestore import ShardFilestore, ShardMetadata
from datetime import datetime

logger = logging.getLogger(__name__)


class SynthesisEngine:
    def __init__(self, filestore: ShardFilestore):
        self.filestore = filestore

    def generate_monolithic(self, shard_ids: List[str], app_name: str = "synthesized_app") -> str:
        shards = []
        for sid in shard_ids:
            record = self.filestore.get_shard(sid)
            if record:
                shards.append(record)

        imports = set()
        bodies = []
        for rec in shards:
            for imp in rec.get("import_dependencies", []):
                imports.add(imp)
            source_code = rec.get("source_code", "")
            if source_code:
                bodies.append(source_code)

        header = f'''#!/usr/bin/env python3
# Synthesized Application: {app_name}
# Generated at: {datetime.utcnow().isoformat()}Z
# Shards: {len(shards)}

import argparse
import asyncio
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

'''
        for imp in sorted(imports):
            header += f"{imp}\n"

        body = "\n\n".join(bodies)
        return header + "\n" + body

    def generate_consolidated_package(self, shard_ids: List[str], package_name: str = "synthesized_pkg") -> Dict[str, Any]:
        shards = self._group_by_category(shard_ids)
        structure = {
            "package_name": package_name,
            "files": {},
            "pyproject": self._generate_pyproject(package_name),
            "init_py": "",
        }

        for category, items in shards.items():
            module_name = category
            file_path = f"{module_name}.py"
            imports = set()
            bodies = []
            for sid in items:
                record = self.filestore.get_shard(sid)
                if record:
                    for imp in record.get("import_dependencies", []):
                        imports.add(imp)
                    source_code = record.get("source_code", "")
                    if source_code:
                        bodies.append(source_code)

            file_content = f'''"""
{category.capitalize()} module for {package_name}
Auto-generated by PyShard-P9
"""

'''
            for imp in sorted(imports):
                file_content += f"{imp}\n"
            file_content += "\n\n" + "\n\n".join(bodies)
            structure["files"][file_path] = file_content

        init_items = [f"from .{cat} import *" for cat in shards.keys()]
        structure["init_py"] = "\n".join(init_items)
        return structure

    def _group_by_category(self, shard_ids: List[str]) -> Dict[str, List[str]]:
        groups: Dict[str, List[str]] = {}
        for sid in shard_ids:
            record = self.filestore.get_shard(sid)
            if record:
                cat = record.get("category", "utils")
                groups.setdefault(cat, []).append(sid)
        return groups

    def _generate_pyproject(self, package_name: str) -> str:
        return f'''[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "{package_name}"
version = "0.1.0"
description = "Auto-generated consolidated package"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.100.0",
    "pydantic>=2.0",
    "uvicorn>=0.23.0",
]

[project.optional-dependencies]
dev = ["ruff>=0.1.0", "mypy>=1.0", "pytest>=7.0"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP"]

[tool.mypy]
strict = true
'''

    def deduplicate_shards(self, shard_ids: List[str]) -> List[str]:
        seen = set()
        deduped = []
        for sid in shard_ids:
            record = self.filestore.get_shard(sid)
            if not record:
                continue
            source = record.get("source_code", "")
            key = hashlib.sha256(source.encode()).hexdigest() if source else sid
            if key not in seen:
                seen.add(key)
                deduped.append(sid)
        return deduped

    def topological_sort(self, shard_ids: List[str]) -> Tuple[List[str], List[str]]:
        graph: Dict[str, set] = {sid: set() for sid in shard_ids}
        for sid in shard_ids:
            record = self.filestore.get_shard(sid)
            if not record:
                continue
            for dep in record.get("import_dependencies", []):
                for other in shard_ids:
                    if other != sid:
                        other_rec = self.filestore.get_shard(other)
                        if other_rec and other_rec.get("name") in dep:
                            graph[sid].add(other)

        cycles = self._find_cycles(graph)
        if cycles:
            logger.warning(f"Circular dependency detected among shards: {cycles}")

        visited = set()
        result = []

        def visit(nid, stack):
            if nid in visited:
                return
            visited.add(nid)
            stack.add(nid)
            for dep in graph.get(nid, set()):
                if dep in stack:
                    logger.warning(f"Cycle detected: {nid} -> {dep}")
                    continue
                visit(dep, stack)
            stack.discard(nid)
            result.append(nid)

        for sid in shard_ids:
            visit(sid, set())
        return result, cycles

    def _find_cycles(self, graph: Dict[str, set]) -> List[str]:
        visited = set()
        rec_stack = set()
        cycles = []

        def dfs(node, path):
            visited.add(node)
            rec_stack.add(node)
            path.append(node)
            for neighbor in graph.get(node, set()):
                if neighbor not in visited:
                    dfs(neighbor, path)
                elif neighbor in rec_stack:
                    cycle_start = path.index(neighbor)
                    cycle = path[cycle_start:]
                    cycles.append(" -> ".join(cycle))
            path.pop()
            rec_stack.discard(node)

        for node in graph:
            if node not in visited:
                dfs(node, [])
        return cycles
