import json
import logging

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional

from backend.core import SynthesisEngine, ShardFilestore, LexicalNormalizer, RegexNormalizer, EnvironmentProvisioner
from backend.core.filestore import ShardMetadata
from datetime import datetime

logger = logging.getLogger(__name__)
router = APIRouter()

filestore = ShardFilestore()
synthesis = SynthesisEngine(filestore)
normalizer = LexicalNormalizer()
regex_norm = RegexNormalizer()
provisioner = EnvironmentProvisioner()


class SynthesisRequest(BaseModel):
    shard_ids: List[str]
    mode: str = "monolithic"
    app_name: str = "synthesized_app"
    apply_normalization: bool = True
    package_name: Optional[str] = None


class BlueprintRequest(BaseModel):
    shard_ids: List[str]
    app_name: str = "blueprint_app"


class CompatibilityResponse(BaseModel):
    compatible: bool
    conflicts: List[str]
    missing_links: List[str]


@router.post("/monolithic")
async def synthesize_monolithic(request: SynthesisRequest):
    deduped = synthesis.deduplicate_shards(request.shard_ids)
    sorted_ids, cycles = synthesis.topological_sort(deduped)
    if cycles:
        logger.warning(f"Circular dependencies detected: {cycles}")
    code = synthesis.generate_monolithic(sorted_ids, app_name=request.app_name)

    if request.apply_normalization:
        code = regex_norm.normalize(code)

    return {"mode": "monolithic", "app_name": request.app_name, "code": code, "shards_used": len(sorted_ids)}


@router.post("/package")
async def synthesize_package(request: SynthesisRequest):
    deduped = synthesis.deduplicate_shards(request.shard_ids)
    sorted_ids, cycles = synthesis.topological_sort(deduped)
    if cycles:
        logger.warning(f"Circular dependencies detected: {cycles}")
    pkg_name = request.package_name or request.app_name.replace(" ", "_").lower()
    structure = synthesis.generate_consolidated_package(sorted_ids, package_name=pkg_name)

    if request.apply_normalization:
        for path, content in structure["files"].items():
            structure["files"][path] = regex_norm.normalize(content)
        structure["init_py"] = regex_norm.normalize(structure["init_py"])

    return structure


@router.post("/blueprint")
async def generate_blueprint(request: BlueprintRequest):
    shards = []
    for sid in request.shard_ids:
        record = filestore.get_shard(sid)
        if record:
            shards.append(record)

    dependencies = {}
    for shard in shards:
        deps = json.loads(shard.get("import_dependencies", "[]") or "[]")
        dependencies[shard["shard_id"]] = deps

    blueprint = f"""# Architectural Blueprint: {request.app_name}

## Overview
Generated by PyShard-P9 at {datetime.utcnow().isoformat()}Z

## Selected Shards ({len(shards)})
"""
    for shard in shards:
        blueprint += f"- `{shard['name']}` ({shard['shard_type']}, category: {shard['category']})\n"

    blueprint += "\n## Dependency Mapping\n"
    for sid, deps in dependencies.items():
        shard = next((s for s in shards if s["shard_id"] == sid), None)
        if shard:
            blueprint += f"- `{shard['name']}` depends on: {', '.join(deps) if deps else 'none'}\n"

    conflicts = []
    all_deps = []
    for deps in dependencies.values():
        all_deps.extend(deps)

    dep_counts = {}
    for dep in all_deps:
        dep_counts[dep] = dep_counts.get(dep, 0) + 1
    conflicts = [d for d, c in dep_counts.items() if c > 1]

    blueprint += f"\n## Architectural Warnings\n"
    if conflicts:
        blueprint += f"- Conflicting dependencies detected: {', '.join(conflicts)}\n"
    else:
        blueprint += "- No conflicting dependencies detected.\n"

    return {"blueprint": blueprint, "shards_count": len(shards), "conflicts": conflicts}


@router.post("/compatibility", response_model=CompatibilityResponse)
async def check_compatibility(shard_ids: List[str]):
    conflicts = []
    missing_links = []
    seen_names = set()

    for sid in shard_ids:
        record = filestore.get_shard(sid)
        if not record:
            missing_links.append(f"Shard {sid} not found in filestore")
            continue
        name = record.get("name", "")
        if name in seen_names:
            conflicts.append(f"Duplicate shard name: {name}")
        seen_names.add(name)

        deps = json.loads(record.get("import_dependencies", "[]") or "[]")
        for dep in deps:
            found = False
            for other_id in shard_ids:
                if other_id != sid:
                    other = filestore.get_shard(other_id)
                    if other and other.get("name") in dep:
                        found = True
                        break
            if not found:
                missing_links.append(f"`{name}` requires `{dep}` but no provider shard selected")

    return {
        "compatible": len(conflicts) == 0 and len(missing_links) == 0,
        "conflicts": conflicts,
        "missing_links": missing_links,
    }


@router.post("/normalize")
async def normalize_code(code: str, old_root: str = "", new_root: str = ""):
    regex_norm = RegexNormalizer()
    normalized = regex_norm.normalize(code)
    if old_root and new_root:
        normalized = regex_norm.normalize_paths(normalized, old_root, new_root)
    return {"original": code, "normalized": normalized}


@router.post("/env")
async def generate_env(imports: List[str], variables: List[str], package_name: str = "synthesized_pkg"):
    reqs = provisioner.generate_requirements(imports)
    pyproject = provisioner.generate_pyproject(package_name, dependencies=imports)
    env_template = provisioner.generate_env_template(variables)
    validation = provisioner.generate_validation_script()
    return {
        "requirements_txt": reqs,
        "pyproject_toml": pyproject,
        "env_template": env_template,
        "validation_script": validation,
    }
