"""Shadow agent - background worker for auto-loadouts and micro-tools."""

import asyncio
import json
import logging
import subprocess
import shutil
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..config import HarnessConfig
from ..models import ShadowDelta


class ShadowAgent:
    """
    Background worker for the shadow agent.
    
    Functions:
    - Auto-loadouts on session start
    - Error interception and micro-tool generation
    - Context-Time Training (CTT) and ICRL
    """
    
    def __init__(self, config: HarnessConfig):
        self.config = config
        self.logger = logging.getLogger("agnostic.shadow.agent")
        self.task_queue: List[Dict[str, Any]] = []
        self.running = False
        self.learning_buffer: List[Dict[str, Any]] = []
    
    async def start(self):
        """Start the shadow agent background worker."""
        self.running = True
        self.logger.info("Shadow Agent started")
        
        await self._auto_loadout()
        
        while self.running:
            await self._process_next_task()
            await asyncio.sleep(1)
    
    async def stop(self):
        """Stop the shadow agent."""
        self.running = False
        self.logger.info("Shadow Agent stopped")
    
    async def _auto_loadout(self):
        """Execute auto-loadout on session start."""
        self.logger.info("Running auto-loadout...")
        
        human_dir = self.config.human_dir
        for subdir in ["tools", "skills", "memory", "config"]:
            (human_dir / subdir).mkdir(parents=True, exist_ok=True)
        
        manifest_path = human_dir / "tools" / "manifest.json"
        if manifest_path.exists():
            self.logger.info(f"Loaded manifest from {manifest_path}")
        else:
            manifest_path.write_text(json.dumps({"tools": {}}, indent=2))
        
        self.logger.info("Auto-loadout complete")
    
    async def _process_next_task(self):
        """Process the next task in the queue."""
        if not self.task_queue:
            return
        
        task = self.task_queue.pop(0)
        self.logger.info(f"Processing shadow task: {task.get('type')}")
        
        try:
            task_type = task.get("type")
            
            if task_type == "auto_loadout":
                result = await self._auto_loadout()
            elif task_type == "error_intercept":
                result = await self._intercept_error(task.get("payload", {}))
            elif task_type == "micro_tool_gen":
                result = await self._generate_micro_tool(task.get("payload", {}))
            elif task_type == "research":
                result = await self._background_research(task.get("payload", {}))
            else:
                result = {"status": "unknown_task_type"}
            
            task["status"] = "completed"
            task["result"] = result
            
            self.learning_buffer.append({
                "task_id": task.get("id"),
                "type": task_type,
                "result": result,
                "timestamp": datetime.utcnow().isoformat(),
            })
            
        except Exception as e:
            task["status"] = "failed"
            task["result"] = {"error": str(e)}
            self.logger.error(f"Shadow task failed: {e}")
    
    async def _intercept_error(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Intercept tool execution errors."""
        stderr = payload.get("stderr", "")
        task_id = payload.get("task_id", "unknown")
        
        self.logger.warning(f"Intercepting error for task {task_id}")
        
        error_patterns = {
            "ModuleNotFoundError": "pip install",
            "ImportError": "pip install",
            "Command not found": "cargo install",
            "Permission denied": "chmod +x",
            "No such file or directory": "create file",
        }
        
        for pattern, action in error_patterns.items():
            if pattern in stderr:
                return {
                    "action": action,
                    "pattern": pattern,
                    "auto_fixable": True,
                }
        
        return {"action": "unknown", "auto_fixable": False}
    
    async def _generate_micro_tool(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a micro-tool to handle a missing/failing tool."""
        task_id = payload.get("task_id", "unknown")
        error = payload.get("error", "")
        
        tool_path = self.config.harness_dir / "tools" / f"micro_tool_{task_id}.py"
        
        content = f"""#!/usr/bin/env python3
\"\"\"
Micro-tool generated by Shadow Agent
Task: {task_id}
Error: {error[:100]}
\"\"\"

import subprocess
import sys

def main():
    print("Micro-tool placeholder - implement specific fix here")
    return 0

if __name__ == "__main__":
    sys.exit(main())
"""
        tool_path.write_text(content)
        tool_path.chmod(0o755)
        
        return {
            "tool_path": str(tool_path),
            "status": "generated",
        }
    
    async def _background_research(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Perform background research."""
        query = payload.get("query", "")
        self.logger.info(f"Background research: {query}")
        
        return {
            "status": "research_complete",
            "query": query,
            "results_count": 0,
        }
    
    def queue_task(self, task_type: str, payload: Dict[str, Any]) -> str:
        """Queue a new task for the shadow agent."""
        task_id = f"shadow_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}"
        task = {
            "id": task_id,
            "type": task_type,
            "payload": payload,
            "status": "pending",
        }
        self.task_queue.append(task)
        self.logger.info(f"Queued shadow task: {task_type}")
        return task_id
    
    def get_learning_summary(self) -> Dict[str, Any]:
        """Get summary of learning from ICRL buffer."""
        return {
            "total_experiences": len(self.learning_buffer),
            "recent_experiences": self.learning_buffer[-10:],
        }
