#!/bin/bash
# angel-self-improve v3 — Self-Evolution Engine with Mycelium Integration
# Merges learning capture + skill extraction + mycelium cross-pollination
# into a single evolution system.
#
# Mycelium patterns integrated:
#   - FORAGE: Cross-pollination between domains
#   - DIG: Deep pattern analysis
#   - CONNECT: Bridge concepts across fields
#   - TRACK: Domain exploration logging
#   - CHALLENGE: Self-critique of evolution patterns

ANGEL_HOME="${ANGEL_HOME:-$HOME/.angelkernel}"
source "$ANGEL_HOME/lib/angel-lib.sh" 2>/dev/null || true
ANGEL_SCRIPT="self-improve"
angel_console_init 2>/dev/null || true

LEARNINGS_DIR="$ANGEL_HOME/memory/learnings"
SKILLS_DIR="$ANGEL_HOME/skills"
MYCELIUM_DIR="$ANGEL_HOME/memory/mycelium"
mkdir -p "$LEARNINGS_DIR" "$SKILLS_DIR" "$MYCELIUM_DIR"

LEARNINGS_FILE="$LEARNINGS_DIR/LEARNINGS.md"
ERRORS_FILE="$LEARNINGS_DIR/ERRORS.md"
FEATURES_FILE="$LEARNINGS_DIR/FEATURES.md"
MYCELIUM_PROFILE="$MYCELIUM_DIR/mycelium-profile.md"
MYCELIUM_CROSSPOLLINATION="$MYCELIUM_DIR/cross-pollination.json"

for f in "$LEARNINGS_FILE" "$ERRORS_FILE" "$FEATURES_FILE"; do
    [ ! -f "$f" ] && echo "# $(basename "$f" .md)" > "$f"
done

if [ ! -f "$MYCELIUM_PROFILE" ]; then
    cat > "$MYCELIUM_PROFILE" << 'PROFILE'
# Mycelium — Domain & Learning Profile
Generated by AngelKernel Self-Evolution Engine v3

## Domains Explored
(tracked automatically)
PROFILE
fi

if [ ! -f "$MYCELIUM_CROSSPOLLINATION" ]; then
    echo '{"bridges": [], "cross_pollinations": [], "last_forage": null}' > "$MYCELIUM_CROSSPOLLINATION"
fi

# ============================================================================
# LOG LEARNING — Store with enough context for mycelium analysis
# ============================================================================

log_learning() {
    local domain="$1"
    local area="$2"
    local content="$3"
    local id="LRN-$(date +%s)"
    
    # Log the learning
    {
        echo ""
        echo "## $id"
        echo "- **Domain**: $domain"
        echo "- **Area**: $area"
        echo "- **Date**: $(date)"
        echo "- **Content**: $content"
    } >> "$LEARNINGS_FILE"
    
    # Update mycelium domain tracking
    local domain_clean
    domain_clean=$(echo "$domain" | tr -c 'a-zA-Z0-9_-' '_')
    local domain_tracker="$MYCELIUM_DIR/${domain_clean}.md"
    if [ ! -f "$domain_tracker" ]; then
        echo "# Mycelium Domain: $domain" > "$domain_tracker"
        echo "" >> "$domain_tracker"
        echo "## Learnings" >> "$domain_tracker"
    fi
    echo "- [$(date +%Y-%m-%d)] $area: ${content:0:100}" >> "$domain_tracker"
    
    angel_print "evolve" "LEARN" "id=$id domain=$domain area=$area"
}

# ============================================================================
# LOG ERROR — Track failure patterns for evolution
# ============================================================================

log_error() {
    local domain="$1"
    local area="$2"
    local content="$3"
    local id="ERR-$(date +%s)"
    
    {
        echo ""
        echo "## $id"
        echo "- **Domain**: $domain"
        echo "- **Area**: $area"
        echo "- **Date**: $(date)"
        echo "- **Content**: $content"
        echo "- **Status**: logged for evolution"
    } >> "$ERRORS_FILE"
    
    angel_print "evolve" "ERROR LOG" "id=$id domain=$domain area=$area"
}

# ============================================================================
# EVOLUTION COUNTER INCREMENT — Update evolution DB counters
# ============================================================================

increment_evolution_counters() {
    local type="$1"  # "evolution", "skill", "heal", "refinement"
    local details="${2:-}"
    local evo_file="$ANGEL_HOME/store/evolution/evolution.json"
    
    [ ! -f "$evo_file" ] && return 1
    
    python3 -c "
import json, os
evo_file = '$evo_file'
try:
    with open(evo_file) as f:
        d = json.load(f)
except:
    d = {'version': '3.0.0', 'total_evolutions': 0, 'skills_extracted': 0, 'auto_heals': 0, 'refinements': 0, 'evolution_history': [], 'error_count': 0}

# Increment the appropriate counter
t = '$type'
if t == 'evolution':
    d['total_evolutions'] = d.get('total_evolutions', 0) + 1
elif t == 'skill':
    d['skills_extracted'] = d.get('skills_extracted', 0) + 1
elif t == 'heal':
    d['auto_heals'] = d.get('auto_heals', 0) + 1
elif t == 'refinement':
    d['refinements'] = d.get('refinements', 0) + 1

# Add history entry
from datetime import datetime, timezone
entry = {
    'timestamp': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    'type': t,
    'details': '''${details}'''[:200]
}
d['evolution_history'].append(entry)
# Keep only last 100 entries
d['evolution_history'] = d['evolution_history'][-100:]

with open(evo_file, 'w') as f:
    json.dump(d, f, indent=2)
print('Counter incremented: ' + t)
" 2>/dev/null
}


# ============================================================================
# MYCELIUM FORAGE — Cross-pollinate domains to find unexpected connections
# This is the core mycelium pattern: finding bridges between domains
# ============================================================================

mycelium_forage() {
    angel_print "evolve" "MYCELIUM FORAGE" "cross-pollinating domains..."
    
    local forage_result
    forage_result=$(python3 -c "
import json, sys, re
from collections import Counter

learnings_file = '$LEARNINGS_FILE'
cross_file = '$MYCELIUM_CROSSPOLLINATION'
domain_dir = '$MYCELIUM_DIR'

# Read learnings
domains = []
areas = []
try:
    with open(learnings_file) as f:
        text = f.read()
        # Extract domains from pattern markers
        for line in text.split('\n'):
            if '**Domain**:' in line:
                d = line.split('**Domain**: ')[-1].strip()
                if d: domains.append(d)
            if '**Area**:' in line:
                a = line.split('**Area**: ')[-1].strip()
                if a: areas.append(a)
except: pass

# Count domain frequencies
domain_counts = Counter(domains)
top_domains = [d for d, c in domain_counts.most_common() if c >= 2]

# Find cross-domain bridges
bridges = []
for i in range(len(top_domains)):
    for j in range(i+1, len(top_domains)):
        d1, d2 = top_domains[i], top_domains[j]
        # Check if they share any area
        shared_areas = [a for a in areas if a and (
            a in open(learnings_file).read().split('**Domain**: ' + d1)[-1][:500] and
            a in open(learnings_file).read().split('**Domain**: ' + d2)[-1][:500]
        )] if __import__('os').path.exists(learnings_file) else []
        bridge = {
            'from': d1,
            'to': d2,
            'shared_areas': list(set(shared_areas))[:3],
            'strength': len(shared_areas),
            'discovered': '$(date +%Y-%m-%d)'
        }
        if bridge['strength'] > 0:
            bridges.append(bridge)

# Save cross-pollination data
existing = {'bridges': [], 'cross_pollinations': [], 'last_forage': None}
try:
    with open(cross_file) as f:
        existing = json.load(f)
except: pass

new_bridges = [b for b in bridges if b not in existing.get('bridges', [])]
existing['bridges'] = bridges
existing['cross_pollinations'].extend([{
    'timestamp': '$(date -Iseconds)',
    'bridges_found': len(new_bridges),
    'total_bridges': len(bridges),
    'domains_analyzed': len(top_domains)
}])
existing['last_forage'] = '$(date -Iseconds)'

with open(cross_file, 'w') as f:
    json.dump(existing, f, indent=2)

result = {
    'domains_found': len(top_domains),
    'bridge_count': len(bridges),
    'new_bridges': len(new_bridges),
    'bridges': bridges[:5],  # Top 5
    'has_cross_pollination': len(bridges) >= 2
}
print(json.dumps(result, indent=2))
" 2>/dev/null)
    
    local bridge_count
    bridge_count=$(echo "$forage_result" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('bridge_count',0))" 2>/dev/null || echo "0")
    local domains_found
    domains_found=$(echo "$forage_result" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('domains_found',0))" 2>/dev/null || echo "0")
    local new_bridges
    new_bridges=$(echo "$forage_result" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('new_bridges',0))" 2>/dev/null || echo "0")
    
    echo "$forage_result"
    
    if [ "$new_bridges" -gt 0 ]; then
        angel_info "  🍄 Mycelium: $new_bridges new cross-domain bridge(s) discovered!"
    fi
    angel_info "  🍄 Mycelium: $domains_found domains, $bridge_count total bridges"
}

# ============================================================================
# MYCELIUM CONNECT — Bridge two specific domains (intentional connection)
# ============================================================================

mycelium_connect() {
    local domain_a="$1"
    local domain_b="$2"
    
    angel_print "evolve" "MYCELIUM CONNECT" "bridging '$domain_a' ↔ '$domain_b'..."
    
    python3 -c "
import json, sys

learnings_file = '$LEARNINGS_FILE'
domain_a = '$domain_a'
domain_b = '$domain_b'

# Find all learnings for each domain
learnings_a = []
learnings_b = []
current_domain = ''
current_learning = ''

try:
    with open(learnings_file) as f:
        for line in f:
            if '**Domain**:' in line:
                current_domain = line.split('**Domain**: ')[-1].strip()
                current_learning = ''
            elif '**Content**:' in line:
                current_learning = line.split('**Content**: ')[-1].strip()
                if current_domain == domain_a:
                    learnings_a.append(current_learning)
                elif current_domain == domain_b:
                    learnings_b.append(current_learning)
except: pass

# Find shared concepts (word overlap)
words_a = set()
for l in learnings_a:
    words_a.update(l.lower().split())
words_b = set()
for l in learnings_b:
    words_b.update(l.lower().split())

shared = words_a & words_b
# Filter common words
stop_words = {'the', 'a', 'an', 'to', 'in', 'for', 'of', 'is', 'on', 'and', 'or', 'with', 'this', 'that', 'from', 'by', 'at', 'be'}
shared = shared - stop_words

result = {
    'domain_a': domain_a,
    'domain_b': domain_b,
    'learnings_a': len(learnings_a),
    'learnings_b': len(learnings_b),
    'shared_concepts': list(shared)[:10],
    'shared_count': len(shared),
    'connection_strength': min(len(shared) / 5, 1.0)
}
print(json.dumps(result, indent=2))
" 2>/dev/null
}

# ============================================================================
# MYCELIUM DIG — Deep analysis into a specific domain's pattern evolution
# ============================================================================

mycelium_dig() {
    local domain="${1:-all}"
    
    angel_print "evolve" "MYCELIUM DIG" "deep analysis of domain: $domain..."
    
    python3 -c "
import json, sys
from collections import Counter

learnings_file = '$LEARNINGS_FILE'
domain_filter = '$domain'

# Parse learnings
records = []
current = {}
try:
    with open(learnings_file) as f:
        for line in f:
            if line.startswith('## LRN-'):
                if current: records.append(current)
                current = {'id': line.strip('# \n')}
            elif '**Domain**:' in line:
                current['domain'] = line.split('**Domain**: ')[-1].strip()
            elif '**Area**:' in line:
                current['area'] = line.split('**Area**: ')[-1].strip()
            elif '**Date**:' in line:
                current['date'] = line.split('**Date**: ')[-1].strip()
            elif '**Content**:' in line:
                current['content'] = line.split('**Content**: ')[-1].strip()[:100]
        if current: records.append(current)
except: pass

# Filter by domain
if domain_filter != 'all':
    records = [r for r in records if r.get('domain') == domain_filter]

# Analyze
domains = Counter(r.get('domain', 'unknown') for r in records)
areas = Counter(r.get('area', 'unknown') for r in records)

result = {
    'domain': domain_filter,
    'total_learnings': len(records),
    'unique_domains': len(domains),
    'top_domains': domains.most_common(5),
    'top_areas': areas.most_common(5),
    'recent_learnings': records[-5:] if len(records) >= 5 else records,
    'evolution_health': 'strong' if len(records) >= 10 else ('developing' if len(records) >= 5 else 'early')
}
print(json.dumps(result, indent=2))
" 2>/dev/null
}

# ============================================================================
# EXTRACT SKILLS — Find patterns repeating 3+ times, plus mycelium bridge skills
# ============================================================================

extract_skills() {
    angel_lock "skill-extraction" || {
        echo "[self-improve] Skill extraction already in progress — skipping"
        return 0
    }
    
    angel_print "evolve" "EXTRACT SKILLS" "scanning for patterns ≥3 occurrences"
    
    # Step 1: Extract from learnings (existing logic)
    local patterns
    patterns=$(grep -oP '(?<=\*\*Domain\*\*: ).*' "$LEARNINGS_FILE" 2>/dev/null | sort | uniq -c | sort -rn)
    
    echo "$patterns" | while read -r count pattern; do
        if [ "$count" -ge 3 ]; then
            local skill_name="extracted-$(echo "$pattern" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-')"
            local skill_dir="$SKILLS_DIR/$skill_name"
            if [ ! -d "$skill_dir" ]; then
                mkdir -p "$skill_dir"
                cat > "$skill_dir/SKILL.md" << SKILL
# $skill_name

## Origin
Auto-extracted from recurring learning domain: "$pattern" ($count occurrences)

## Mycelium Context
- **Extracted**: $(date)
- **Domain**: $pattern
- **Frequency**: $count occurrences

## Pattern
$pattern

## Cross-Domain Connections
_(Mycelium will populate bridge connections here)_

## Usage
Applied automatically by AngelKernel when domain is detected.
SKILL
                echo "[self-improve] Extracted skill: $skill_name (domain: $pattern, $count occurrences)"
                increment_evolution_counters "skill" "Extracted $skill_name from domain $pattern ($count occurrences)"
                
                # Log mycelium-style domain extraction
                echo "- $(date): Extracted skill '$skill_name' from domain '$pattern' ($count occurrences)" >> "$MYCELIUM_PROFILE"
            fi
        fi
    done
    
    # Step 2: MYCELIUM INTEGRATION — Extract cross-domain bridge skills
    # If two domains have been connected by mycelium >=2 times, extract as bridge skill
    if [ -f "$MYCELIUM_CROSSPOLLINATION" ]; then
        python3 -c "
import json, sys
from collections import Counter

cross_file = '$MYCELIUM_CROSSPOLLINATION'
skills_dir = '$SKILLS_DIR'
mycelium_profile = '$MYCELIUM_PROFILE'

try:
    with open(cross_file) as f:
        data = json.load(f)
    
    bridges = data.get('bridges', [])
    # Find strong bridges (strength >= 2)
    strong_bridges = [b for b in bridges if b.get('strength', 0) >= 2]
    
    for bridge in strong_bridges:
        d1 = bridge.get('from', '')
        d2 = bridge.get('to', '')
        strength = bridge.get('strength', 0)
        shared = bridge.get('shared_areas', [])
        
        if d1 and d2:
            skill_name = f'bridge-{d1}-{d2}'
            skill_dir = f'{skills_dir}/{skill_name}'
            
            # Only create if not exists
            if not __import__('os').path.exists(skill_dir):
                __import__('os').makedirs(skill_dir, exist_ok=True)
                
                skill_content = f'''# {skill_name}

## Mycelium Bridge Skill
Auto-extracted cross-domain bridge between "{d1}" and "{d2}"

## Bridge Strength: {strength}
- **From**: {d1}
- **To**: {d2}
- **Shared Areas**: {', '.join(shared[:3]) if shared else 'structural'}

## Usage
Applied when tasks require cross-domain thinking between {d1} and {d2}.
'''
                with open(f'{skill_dir}/SKILL.md', 'w') as sf:
                    sf.write(skill_content)
                
                # Log to mycelium profile
                with open(mycelium_profile, 'a') as mp:
                    mp.write(f'- $(date): Bridge skill created: {d1} ↔ {d2} (strength: {strength})\\n')
                
                print(f'Bridge skill: {skill_name} ({d1} ↔ {d2}, strength: {strength})')
    
    # Get stats
    bridge_count = len(strong_bridges)
    total_bridges = len(bridges)
    with open('$MYCELIUM_CROSSPOLLINATION') as f:
        data = json.load(f)
    data['last_extraction'] = '$(date -Iseconds)'
    with open('$MYCELIUM_CROSSPOLLINATION', 'w') as f:
        json.dump(data, f, indent=2)
    
    if bridge_count > 0:
        print(f'Created {bridge_count} bridge skill(s) from {total_bridges} total bridge(s)')
except Exception as e:
    print(f'Bridge extraction skipped: {e}')
" 2>/dev/null
    fi
    
    angel_unlock "skill-extraction"
}

# ============================================================================
# MYCELIUM TRACK — Show full domain exploration status
# ============================================================================

mycelium_track() {
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║  Mycelium — Domain & Learning Tracker                       ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    
    echo "📊 Learning Statistics:"
    echo "────────────────────────────────────────────"
    local learning_count error_count
    learning_count=$(grep -c '^## LRN-' "$LEARNINGS_FILE" 2>/dev/null || echo 0)
    error_count=$(grep -c '^## ERR-' "$ERRORS_FILE" 2>/dev/null || echo 0)
    echo "  Learnings: $learning_count"
    echo "  Errors logged: $error_count"
    
    echo ""
    echo "🍄 Mycelium Cross-Pollination:"
    echo "────────────────────────────────────────────"
    if [ -f "$MYCELIUM_CROSSPOLLINATION" ]; then
        python3 -c "
import json
with open('$MYCELIUM_CROSSPOLLINATION') as f:
    d = json.load(f)
bridges = d.get('bridges', [])
print(f'  Total bridges: {len(bridges)}')
for b in bridges[:5]:
    print(f'  • {b.get(\"from\",\"?\")} ↔ {b.get(\"to\",\"?\")} (strength: {b.get(\"strength\",0)})')
if len(bridges) > 5:
    print(f'  ... and {len(bridges)-5} more')
" 2>/dev/null
    fi
    
    echo ""
    echo "🔧 Extracted Skills:"
    echo "────────────────────────────────────────────"
    for skill_dir in "$SKILLS_DIR"/extracted-*/ "$SKILLS_DIR"/bridge-*/; do
        if [ -d "$skill_dir" ]; then
            local name
            name=$(basename "$skill_dir")
            echo "  • $name"
        fi
    done
    
    echo ""
    echo "🏷️  Tracked Domains:"
    echo "────────────────────────────────────────────"
    for domain_file in "$MYCELIUM_DIR"/*.md; do
        if [ -f "$domain_file" ] && [ "$(basename "$domain_file")" != "mycelium-profile.md" ]; then
            local domain_name
            domain_name=$(basename "$domain_file" .md)
            local count
            count=$(grep -c "\[" "$domain_file" 2>/dev/null || echo 0)
            echo "  • $domain_name ($count learnings)"
        fi
    done
}

# ============================================================================
# FULL EVOLVE CYCLE — Complete evolution with mycelium integration
# ============================================================================

full_evolve() {
    local domain="$1"
    local area="$2"
    local content="$3"
    
    angel_print "evolve" "FULL EVOLVE" "domain=$domain area=$area"
    
    # 1. Log the learning
    log_learning "$domain" "$area" "$content"
    
    # 2. Run mycelium forage (cross-pollination)
    mycelium_forage > /dev/null 2>&1
    
    # 3. Extract skills from patterns
    extract_skills > /dev/null 2>&1
    
    # 4. Run mycelium dig on all domains for health check
    local health
    health=$(mycelium_dig "all" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('evolution_health','early'))" 2>/dev/null || echo "early")
    
    # 5. Track mycelium
    echo "- [$(date '+%Y-%m-%d %H:%M')] Evolve: $domain/$area" >> "$MYCELIUM_PROFILE"
    
    increment_evolution_counters "evolution" "Full evolve cycle: $domain/$area"
    echo "[self-improve] Evolution complete — health: $health"
}

# ============================================================================
# MAIN DISPATCH
# ============================================================================

case "${1:-}" in
    --learn)
        shift
        log_learning "$1" "$2" "$3"
        ;;
    --error)
        shift
        log_error "$1" "$2" "$3"
        ;;
    --extract)
        extract_skills
        ;;
    --evolve)
        shift
        full_evolve "auto-evolve" "system" "$*"
        ;;
    --forage|mycelium-forage)
        mycelium_forage
        ;;
    --connect|mycelium-connect)
        shift
        mycelium_connect "$1" "$2"
        ;;
    --dig|mycelium-dig)
        shift
        mycelium_dig "$1"
        ;;
    --track|mycelium-track)
        mycelium_track
        ;;
    *)
        echo "AngelKernel Self-Improvement Engine v3 — with Mycelium Integration"
        echo ""
        echo "Usage:"
        echo "  angel-self-improve --learn <domain> <area> <content>"
        echo "  angel-self-improve --error <domain> <area> <content>"
        echo "  angel-self-improve --extract"
        echo "  angel-self-improve --evolve <context>"
        echo ""
        echo "Mycelium commands:"
        echo "  angel-self-improve --forage              — Cross-pollinate domains"
        echo "  angel-self-improve --connect <a> <b>     — Bridge two domains"
        echo "  angel-self-improve --dig [domain]        — Deep analysis of domain"
        echo "  angel-self-improve --track               — Show full tracker"
        ;;
esac
